-- 삼천포신항-제주항 노선(현성MCT 오션비스타제주호) 차량 운임 — 2026-07-31 기준 공식
-- 홈페이지(oceanvista.co.kr) '정상요금' 컬럼 조사 데이터. 국산 승용차/전기차/화물차/캠핑카/외제차
-- 36개 등급. 사이트 자체에 평일/주말 요금 구분이 없어 weekday_fare=holiday_fare로 동일하게 넣는다.
-- 오토바이/버스 등급은 이 플랫폼이 실제 취급하는 차종과 거리가 있어 제외했다.
insert into ferry_fare_rules
  (route_code, ship_name, vehicle_label, weekday_fare, holiday_fare, source_title, source_url, sort_order, is_active)
select v.route_code, v.ship_name, v.vehicle_label, v.weekday_fare, v.holiday_fare, v.source_title, v.source_url, v.sort_order, v.is_active
from (values
    ('SAMCHEONPO_JEJU', '오션비스타제주', '마티즈, 모닝, 비스토, 스파크, 아토스, 포니', 130000, 130000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 1, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '다마스, 라보, 레이, 캐스퍼, 클릭, 프라이드', 138000, 138000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 2, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'i30, 리오, 베르나, 세라토, 아베오, 아벨라, 엑센트, 젠트라, 칼로스, 클리오', 152000, 152000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 3, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'K3, QM3, SM3, 라비타, 라세티, 베뉴, 벨로스터, 셀토스, 스토닉, 스펙트라, 아반떼, 아이오닉, 캡처, 코나, 크레도스, 크루즈, 투스카니, 트랙스, 티볼리, 포르테', 168000, 168000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 4, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'G70, i40, K5, SM5, SM6, XM3, 니로, 레조, 레토나, 로체, 리갈, 말리부, 매그너스, 소나타, 스팅어, 쏘울, 엑스트랙, 옵티마, 제네시스쿠페, 카렌스, 토스카, 트레블레이저, 프린스', 183000, 183000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 5, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'GV60, K7, K8, SM7, 그랜저, 넥쏘, 스테이츠맨, 스포티지, 알페온, 올란도, 임팔라, 카스타, 코란도C, 투싼, 포텐샤', 201000, 201000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 6, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'EQ900, G80, G90, GV70, K9, QM5, QM6, 갤로퍼, 그랑콜레오스, 다이너스티, 렉스턴, 무쏘, 싼타페, 쏘렌토, 아슬란, 액티언, 에쿠스, 오피러스, 윈스톰, 이쿼녹스, 제네시스 BH330, 제네시스 DH, 체어맨, 카이런, 캡티바, 코란도, 테라칸, 토레스, 트라제, 필랑트', 212000, 212000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 7, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '맥스크루즈, 베라크루즈, 산타크루즈', 236000, 236000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 8, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'GV80, 렉스턴 스포츠, 모하비, 무쏘 스포츠, 액티언 스포츠, 코란도 스포츠, 팰리세이드', 247000, 247000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 9, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '그랜드스타렉스, 그랜드카니발, 그레이스투어, 로디우스, 스타리아, 이스타나, 콜로라도, 타스만, 토픽, 투리스모, 트래버스, 프레지오', 258000, 258000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 10, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '벤츠 스마트(전기차), 삼성 트위지(전기차), 쎄보-C(전기차), 에디슨 EV D2(전기차), 에디슨 EVZ(전기차)', 98000, 98000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 11, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'E-토비(전기차), 레이(전기차), 캐스퍼 EV(전기차)', 138000, 138000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 12, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'SM3(전기차), 볼트(전기차), 아이오닉(전기차), 조에(전기차), 코나(전기차)', 168000, 168000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 13, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'EV3(전기차), EV4(전기차), 니로(전기차), 쏘울(전기차)', 183000, 183000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 14, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'EV6(전기차), GV60(전기차), 아이오닉5(전기차), 아이오닉6(전기차), 코란도(전기차)', 201000, 201000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 15, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'EV5(전기차), G80(전기차), GV70(전기차), 토레스 EV(전기차)', 212000, 212000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 16, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'EV9(전기차), GV80(전기차), PV5(전기차), 무쏘 EV(전기차), 아이오닉9(전기차)', 247000, 247000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 17, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '쎄아(전기차), 이티밴(전기차)', 258000, 258000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 18, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '1톤(공차)(전기차)', 192000, 192000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 19, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '1톤(적차)(전기차)', 217000, 217000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 20, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '1.2톤(공차), 1.4톤(공차), ST1(공차)', 214000, 214000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 21, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '1.2톤(적차), 1.4톤(적차), ST1(적차)', 244000, 244000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 22, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '국산 캠핑카(5m미만), 국산 캠핑트레일러(5m미만)', 285000, 285000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 23, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '국산 캠핑카(5m~6m미만), 국산 캠핑트레일러(5m~6m미만)', 350000, 350000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 24, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '국산 캠핑카(6m~7m미만), 국산 캠핑트레일러(6m~7m미만)', 380000, 380000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 25, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '국산 캠핑카(7m~8m미만), 국산 캠핑트레일러(7m~8m미만)', 412000, 412000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 26, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '외제 캠핑카(5m미만), 외제 캠핑트레일러(5m미만)', 311000, 311000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 27, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '외제 캠핑카(5m~6m미만), 외제 캠핑트레일러(5m~6m미만)', 375000, 375000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 28, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '외제 캠핑카(6m~7m미만), 외제 캠핑트레일러(6m~7m미만)', 405000, 405000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 29, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', '외제 캠핑카(7m~8m미만), 외제 캠핑트레일러(7m~8m미만)', 437000, 437000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 30, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'BMW 1시리즈, BMW 2시리즈, BMW 3시리즈, BMW 4시리즈, BMW X1, BMW X2, BMW Z4, DS3, 닛산 쥬크, 닛산 캐시카이, 닛산 큐브, 닛산 피가로, 렉서스 CT, 링컨 LS, 링컨 MKZ, 마쯔다 MX-5, 미니 S, 미니 SD, 미니 컨버터블, 미니 쿠퍼, 미니 쿠페, 벤츠 A-Class, 벤츠 B-Class, 벤츠 C-Class, 벤츠 CL, 벤츠 CLA, 벤츠 CLK, 벤츠 GLA, 벤츠 GLK, 볼보 C30, 볼보 V40, 스즈키 짐니, 스즈키 허슬러, 시트로엥 C3, 아우디 A1, 아우디 A3, 아우디 A4, 아우디 A5, 아우디 Q2, 아우디 TT, 아우디 TTS, 인피니티 G37, 인피니티 Q30, 지프 레니게이드, 지프 컴패스, 코펜, 크라이슬러 PT크루저, 토요타 비비, 토요타 윌비, 토요타 프리우스, 포드 몬데오, 포드 이스케이프, 포드 포커스, 폭스바겐 골프, 폭스바겐 뉴비틀, 폭스바겐 시로코, 폭스바겐 제타, 폭스바겐 티록, 폭스바겐 폴로, 푸조 206, 푸조 207, 푸조 208, 푸조 307, 푸조 308, 푸조 RCZ, 피아트 500, 혼다 CR-Z, 혼다 HR-V, 혼다 N1, 혼다 S660, 혼다 시빅', 212000, 212000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 31, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'BMW 5시리즈, BMW 6시리즈, BMW X3, BMW X4, DS4, DS5, DS6, DS7, 닛산 로그, 닛산 맥시마, 닛산 무라노, 닛산 알티마, 닷지 캘리버, 렉서스 ES, 렉서스 IS, 렉서스 NX, 렉서스 RC, 렉서스 SC, 렉서스 UX, 링컨 MKC, 링컨 노틸러스, 링컨 코세어, 미니 컨트리맨, 미니 클럽맨, 미쓰비시 RVR, 미쓰비시 랜서, 미쓰비시 랜서 에볼루션, 미쓰비시 아웃랜더, 미쓰비시 이클립스, 벤츠 CLE, 벤츠 CLS, 벤츠 E-Class, 벤츠 GLB, 벤츠 GLC, 볼보 S40, 볼보 S60, 볼보 V50, 볼보 V60, 볼보 XC40, 볼보 XC60, 쉐보레 S-10, 스바루 레거시, 시트로엥 C4, 아우디 A6, 아우디 Q3, 아우디 RS5, 아우디 RS6, 아우디 S4, 아우디 S5, 아우디 S6, 인피니티 EX35, 인피니티 GX35, 인피니티 M30, 인피니티 Q50, 인피니티 Q70, 인피니티 QX70, 재규어 S, 재규어 X, 재규어 XE, 재규어 XF, 재규어 XJL, 재규어 XJS, 재규어 XK, 캐딜락 CT4, 캐딜락 STS, 크라이슬러 200, 토요타 GR86, 토요타 RAV4, 토요타 수프라, 토요타 아발론, 토요타 캠리, 토요타 크라운, 토요타 GT86, 포드 쿠가, 포드 토러스, 포드 퓨전, 폭스바겐 CC, 폭스바겐 아테온, 폭스바겐 티구안, 폭스바겐 파사트, 푸조 3008, 푸조 408/508, 푸조 5008, 혼다 CR-V, 혼다 레전드, 혼다 스탭왜건, 혼다 어코드', 248000, 248000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 32, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'BMW 7시리즈, BMW 8시리즈, BMW M3, BMW M4, BMW M5, BMW X3M, BMW X4M, BMW X5, BMW X6, 닛산 370Z, 닛산 GT-R, 닛산 엑스테라, 닛산 엑스트레일, 닛산 패스파인더, 랜드로버 디스커버리 스포츠, 랜드로버 이보크, 랜드로버 프리랜더, 렉서스 LS, 렉서스 RX, 링컨 MKS, 링컨 MKX, 링컨 컨티넨탈, 링컨 타운카, 미쓰비시 파제로, 벤츠 GLE, 벤츠 M-Class, 벤츠 S-Class, 벤츠 SL, 볼보 S70, 볼보 S80, 볼보 S90, 볼보 V90, 볼보 XC70, 볼보 XC90, 쉐보레 카마로, 시트로엥 C5, 아우디 A7, 아우디 Q5, 아우디 RS7, 아우디 S7, 인피니티 QX50, 인피니티 QX55, 인피니티 QX60, 인피니티 FX, 재규어 E-페이스, 재규어 F-타입, 재규어 F-페이스, 재규어 I-페이스, 재규어 XJ, 재규어 XJR, 캐딜락 CT5, 캐딜락 CT6, 캐딜락 XT4, 캐딜락 XT5, 토요타 랜드크루저, 토요타 시에나, 토요타 알파드, 토요타 타코마, 토요타 하이랜더, 포르쉐 박스터, 포르쉐 카이맨, 폭스바겐 투아렉, 폭스바겐 페이톤, 혼다 앨리먼트, 혼다 크로스투어', 280000, 280000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 33, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'BMW X7, GMC 시에라, GMC 유콘, 닛산 NV밴, 닛산 타이탄, 닛산 프론티어, 닷지 다코타, 랜드로버 디스커버리, 랜드로버 디펜더, 랜드로버 벨라, 벤츠 AMG GT, 벤츠 AMG GTS, 벤츠 GLS, 아우디 A8, 아우디 Q7, 아우디 Q8, 아우디 S8, 인피니티 QX80, 지프 그랜드 체로키, 지프 랭글러, 지프 체로키, 캐딜락 CTS-V, 캐딜락 XT6, 크라이슬러 퍼시피카, 토요타 세콰이어, 토요타 툰드라, 포드 E150, 포드 랩터, 포드 레인저, 포드 브롱코, 포드 익스페디션, 포드 익스플로러, 포드 트랜짓, 포르쉐 마칸, 폭스바겐 캐디, 혼다 릿지라인, 혼다 오딧세이, 혼다 파일럿, 혼다 호라이즌, 르노마스터 밴, 쉐보레 타호, 외제승용차 밴, 포드 E350', 313000, 313000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 34, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'BMW X5M, BMW X6M, 닷지 램, 랜드로버 레인지로버, 랜드로버 레인지로버 스포츠, 렉서스 LC, 렉서스 LM500H, 렉서스 LX700H, 링컨 네비게이터, 링컨 에비에이터, 마세라티 기블리, 벤츠 G바겐, 벤츠 스프린터, 쉐보레 익스프레스, 쉐보레 스타크래프트, 쉐보레 콜벳, 아우디 RSQ8, 재규어 F-타입SVR, 지프 글래디에이터, 캐딜락 에스컬레이드, 포드 F-150, 포드 F-250, 포드 머스탱, 포르쉐 911, 포르쉐 카이엔, 포르쉐 파나메라, 허머 H1, 허머 H2', 357000, 357000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 35, 1),
    ('SAMCHEONPO_JEJU', '오션비스타제주', 'BMW I8, BMW M8, 람보르기니 전차량, 롤스로이스 전차량, 마세라티 Grecale, 마세라티 MC20, 마세라티 르반떼, 마세라티 콰트로포르테, 맥라렌 전차량, 벤츠 마이바흐, 벤츠 마이바흐GLS, 벤틀리 전차량, 아우디 R8, 애스턴마틴 전차량, 페라리 전차량, 포르쉐 스파이더', 605000, 605000, '현성MCT 오션비스타제주호 차량운임(홈페이지 기준, 평일/주말 요금 구분 없음)', 'https://www.oceanvista.co.kr/theme/main/html/price_car.php', 36, 1)
) as v(route_code, ship_name, vehicle_label, weekday_fare, holiday_fare, source_title, source_url, sort_order, is_active)
where not exists (
  select 1 from ferry_fare_rules existing
  where existing.route_code = 'SAMCHEONPO_JEJU' and existing.ship_name = '오션비스타제주'
);
